### Coleta da tabela sobre Salas Multiplex

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

from constantes import (
    NOMES_TABELAS_2020_2011,
    NOMES_TABELAS_2010_2003,
)

from funcoes import coleta_dados_multiplex

# Configura o navegador
options = webdriver.ChromeOptions()
meu_navegador = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# Cria uma lista vazia para ir guardando as tabelas
lista_de_tabelas = []

for ano in range(2020, 2002, -1):
    
    # Define qual texto usar baseado no ano
    if ano >= 2011:
        texto_busca = NOMES_TABELAS_2020_2011
    elif ano >= 2007:
        texto_busca = NOMES_TABELAS_2010_2003

    # Coleta a tabela do ano específico
    df_temp = coleta_dados_multiplex(meu_navegador, texto_busca, ano)
    
    # Se a tabela foi coletada com sucesso (não é None)
    if df_temp is not None:
        
        # Fazemos a limpeza e adicionamos o ano *antes* de guardar
        # Fica só com as duas primeiras colunas
        if ano >= 2011:
            df_temp = df_temp.iloc[:, :3].copy()
            df_temp = df_temp.drop(df_temp.columns[1], axis=1)
        else:
            df_temp = df_temp.iloc[:, :2].copy()
        
        # Adiciona o ano. Usar colunas[0] é mais seguro que iloc para sobrescrever.
        nome_primeira_coluna = df_temp.columns[0]
        df_temp[nome_primeira_coluna] = ano 
        
        # Guarda a tabela pronta na lista
        lista_de_tabelas.append(df_temp)
        print(f"Tabela de {ano} guardada com sucesso!")
        
    else:
        print(f"ATENÇÃO: Falha ao coletar dados para o ano {ano}.")

if len(lista_de_tabelas) > 0:
    # O pd.concat engole a lista inteira de uma vez e cria o DataFrame final
    df_final = pd.concat(lista_de_tabelas, ignore_index=True)
    
    # Ajusta os cabeçalhos finais
    df_final.columns = ['Ano', 'Total_Salas', 'Total_Salas_2']
    
    print("\n--- Tabela final consolidada: ---")
else:
    print("\nFalha crítica: Nenhuma tabela foi coletada para montar o DataFrame final.")

meu_navegador.quit()

Tabela de 2020 guardada com sucesso!
Tabela de 2019 guardada com sucesso!
Tabela de 2018 guardada com sucesso!
Tabela de 2017 guardada com sucesso!
Tabela de 2016 guardada com sucesso!
Tabela de 2015 guardada com sucesso!
Tabela de 2014 guardada com sucesso!
Tabela de 2013 guardada com sucesso!
Tabela de 2012 guardada com sucesso!
Tabela de 2011 guardada com sucesso!
Tabela de 2010 guardada com sucesso!
Tabela de 2009 guardada com sucesso!
Tabela de 2008 guardada com sucesso!
Tabela de 2007 guardada com sucesso!
Tabela de 2006 guardada com sucesso!
Tabela de 2005 guardada com sucesso!
Tabela de 2004 guardada com sucesso!
Tabela de 2003 guardada com sucesso!

--- Tabela final consolidada: ---

In [ ]:
df_final

     Ano Total_Salas Total_Salas_2
0   2020        2757           NaN
1   2019        2738           NaN
2   2018       2.639           NaN
3   2017       2.544           NaN
4   2016       2.367           NaN
5   2015        2228           NaN
6   2014        2025           NaN
7   2013       1.862           NaN
8   2012       1.697           NaN
9   2011       1.550           NaN
10  2010         NaN         1.393
11  2009         NaN         1.267
12  2008         NaN          1227
13  2007         NaN          1101
14  2006         NaN           996
15  2005         NaN           936
16  2004         NaN           629
17  2003         NaN           552

Preenche os NaNs de Total_Salas com os valores da coluna 'Total_Salas_2 '

In [ ]:
df_final['Total_Salas'] = df_final['Total_Salas'].fillna(df_final['Total_Salas_2'])

df_final = df_final.drop(columns=['Total_Salas_2'])

Ordena os anos em ordem crescente e os define como index da função.

In [ ]:
df_final = df_final.sort_values(by=['Ano', 'Total_Salas'], ascending=True)
df_final.set_index('Ano', inplace=True)

In [ ]:
df_final

     Total_Salas
Ano
2003         552
2004         629
2005         936
2006         996
2007        1101
2008        1227
2009       1.267
2010       1.393
2011       1.550
2012       1.697
2013       1.862
2014        2025
2015        2228
2016       2.367
2017       2.544
2018       2.639
2019        2738
2020        2757

Define o tipo de dado da coluna 'Total_Salas' como inteiro.

In [ ]:
df_final['Total_Salas'] = df_final['Total_Salas'].str.replace('.', '').astype(int)
df_final

      Total_Salas
Ano
2003          552
2004          629
2005          936
2006          996
2007         1101
2008         1227
2009         1267
2010         1393
2011         1550
2012         1697
2013         1862
2014         2025
2015         2228
2016         2367
2017         2544
2018         2639
2019         2738
2020         2757