# Total de filmes lançados ano a ano 1913-2024

In [290]:
%pip install pandas openpyxl -q

Note: you may need to restart the kernel to use updated packages.

In [291]:
import pandas as pd

In [292]:
arquivo = 'filmes.csv'
arquivo2 = 'ancine1995-2024.xlsx'
df = pd.read_csv(arquivo)
df2 = pd.read_excel(arquivo2)
df.head()

                                              Título    data
0                           ANIVERSÁRIO DA VENEZUELA  1953.0
1  EXÉRCITO FRANCÊS LUTA CONTRA COMUNISTAS NA IND...  1952.0
2             ENTREVISTA COM PATRICK GUERRAND HERMÈS  1969.0
3                       REFORMA DO MUSEU DO IPIRANGA  1953.0
4                 MORADORES DE RUA NO VIADUTO DO CHÁ     NaN

In [293]:
df2.head()

,data,Certificado de Produto Brasileiro (CPB),Título,Direção,Gênero,Empresa Produtora Brasileira Majoritária,UF,Empresa Produtora Minoritária Brasileira,UF2,Distribuidora,Máximo de Salas,Público acumulado,Renda (R$) acumulada
0,1995,B0400064200000,A Causa Secreta,Sérgio Bianchi,Ficção,Agravo Produções Cinematográficas,SP,-,-,Riofilme,ND,3,"15.000,00"
1,1995,B0500310700000,"Carlota Joaquina, Princesa Do Brazil",Carla Camurati,Ficção,Copacabana Filmes E Produções,RJ,-,-,Elimar,33,1.286.000,"6.430.000,00"
2,1995,B0500264600000,Carmen Miranda - Bananas Is My Business,Helena Solberg,Documentário,Radiante Filmes,RJ,-,-,Riofilme,ND,15.47,"90.000,00"
3,1995,-,Cinema De Lágrimas,Nelson Pereira Dos Santos,Ficção,Meta Vídeo Produções,RJ,-,-,Riofilme,ND,1.575,"7.500,00"
4,1995,B0300012900000,Efeito Ilha,Luiz Alberto Pereira,Ficção,Lapfilme,SP,-,-,Riofilme,ND,3,"15.000,00"

In [294]:
df["data"] = df["data"].fillna(0).astype(int)
df["data"] = df["data"].astype(int)
df2 = df2.drop(["Certificado de Produto Brasileiro (CPB)", "Direção", "Gênero", "Empresa Produtora Brasileira Majoritária", "UF", "UF2", "Distribuidora", "Máximo de Salas", "Público acumulado", "Renda (R$) acumulada"], axis=1)

In [295]:
df2.head()

,data,Título,Empresa Produtora Minoritária Brasileira
0,1995,A Causa Secreta,-
1,1995,"Carlota Joaquina, Princesa Do Brazil",-
2,1995,Carmen Miranda - Bananas Is My Business,-
3,1995,Cinema De Lágrimas,-
4,1995,Efeito Ilha,-

In [296]:
df["data"].value_counts()

data
1968    3356
1965    1206
1962     605
1964     585
1961     463
        ...
1913       1
1916       1
2016       1
1983       1
2006       1
Name: count, Length: 75, dtype: int64

In [297]:
df_final = pd.concat([df, df2], ignore_index=True)
df_final

,Título,data,Empresa Produtora Minoritária Brasileira
0,ANIVERSÁRIO DA VENEZUELA,1953,NaN
1,EXÉRCITO FRANCÊS LUTA CONTRA COMUNISTAS NA IND...,1952,NaN
2,ENTREVISTA COM PATRICK GUERRAND HERMÈS,1969,NaN
3,REFORMA DO MUSEU DO IPIRANGA,1953,NaN
4,MORADORES DE RUA NO VIADUTO DO CHÁ,0,NaN
...,...,...,...
10938,Vidente Por Acidente,2024,-
10939,Vidro Fumê,2024,-
10940,Votos,2024,Globo Comunicação E Participações S/A
10941,Vovó Ninja,2024,Atenea Producao E Distribuicao Audiovisual Ltda
10942,Zé,2024,-

In [298]:
df_final = df_final.drop_duplicates()

In [299]:
df_final

,Título,data,Empresa Produtora Minoritária Brasileira
0,ANIVERSÁRIO DA VENEZUELA,1953,NaN
1,EXÉRCITO FRANCÊS LUTA CONTRA COMUNISTAS NA IND...,1952,NaN
2,ENTREVISTA COM PATRICK GUERRAND HERMÈS,1969,NaN
3,REFORMA DO MUSEU DO IPIRANGA,1953,NaN
4,MORADORES DE RUA NO VIADUTO DO CHÁ,0,NaN
...,...,...,...
10938,Vidente Por Acidente,2024,-
10939,Vidro Fumê,2024,-
10940,Votos,2024,Globo Comunicação E Participações S/A
10941,Vovó Ninja,2024,Atenea Producao E Distribuicao Audiovisual Ltda
10942,Zé,2024,-

In [300]:
df_final["data"].value_counts()

data
1968    3208
1965    1158
1962     585
1964     546
1961     435
        ...
2236       1
1918       1
1913       1
1916       1
1983       1
Name: count, Length: 99, dtype: int64

In [301]:
quantidade_df = df_final["data"].value_counts().reset_index()
quantidade_df.columns = ["data", "quantidade"]
quantidade_df

    data  quantidade
0   1968        3208
1   1965        1158
2   1962         585
3   1964         546
4   1961         435
..   ...         ...
94  2236           1
95  1918           1
96  1913           1
97  1916           1
98  1983           1

[99 rows x 2 columns]

In [302]:
quantidade_df.to_csv("quantidade_ano.csv", index=False)